name: rayon_flutter_core
description: A starter template for Flutter Apps created by Rayon Studios.
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  formz: ^0.6.1
  go_router: ^12.1.1
  hive: ^2.2.3
  http: ^1.1.2
  http_interceptor: ^2.0.0-beta.7
  intl: ^0.18.1
  path_provider: ^2.1.1

dev_dependencies:
  bloc_test: ^9.1.5
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1
  path_provider_platform_interface: ^2.1.1
  plugin_platform_interface: ^2.1.8
  test: ^1.24.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
