name: Flutter Development Workflow

on:
  push:
    branches:
      - development

jobs:
  semantic-pull-request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  build:
    uses: TrendShakers/rayon_flutter_core/.github/workflows/flutter_package.yml@v1
    with:
      build_env: development

  spell-check:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/spell_check.yml@v1
    with:
      includes: |
        **/*.md
      modified_files_only: false
