name: Flutter Staging Workflow

on:
  push:
    branches:
      - staging

jobs:
  semantic-pull-request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  build:
    uses: ./.github/workflows/flutter_package.yml
    with:
      build_env: staging
    secrets: inherit

  spell-check:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/spell_check.yml@v1
    with:
      includes: |
        **/*.md
      modified_files_only: false
